# Sus Income Balance Dataprep

## Data at a glance
Each file corresponds to a year. The table starts at line 4.

In [28]:
!ls raw_files/

A005748177_138_72_71.csv  A005854177_138_72_71.csv  A005953177_138_72_71.csv
A005803177_138_72_71.csv  A005908177_138_72_71.csv  A010005177_138_72_71.csv
A005819177_138_72_71.csv  A005926177_138_72_71.csv  A010019177_138_72_71.csv
A005833177_138_72_71.csv  A005939177_138_72_71.csv

In [29]:
!head raw_files/A005748177_138_72_71.csv -n 5

## Dataprep

In [41]:
import numpy as np 
import pandas as pd
import io

In [111]:
for file in os.listdir("raw_files"):
    #File year identification
    year=""
    fp = io.open("raw_files/"+file, mode="r", encoding="cp1258")
    for i, line in enumerate(fp):
        if i==2:
            year = line[8:-1]
            break
    fp.close()
    print("Year: "+year)

    #Import
    df = pd.read_csv("raw_files/"+file, 
                        sep=";", decimal=".", skiprows=3, 
                        quotechar='"', encoding="cp1258")

    #Separate the city IBGE code
    df['cod_municipio'] = df['Munic-BR'].apply(lambda x: x[0:6])

    #Convert to numeric strings with different decimal char
    for col in df.columns:
        if col not in ["Munic-BR", "cod_municipio"]:
            if df[col].dtype == "object":
                try:
                    df[col] = pd.to_numeric(df[col])
                except:
                    df[col] = pd.to_numeric(df[col].apply(lambda x: x.replace(",",".")), errors="coerce")
                    
    #Operation extract
    print(df.info())
                
    #Output result
    df.to_csv("output_income_balances/health_income_balance_"+year+".csv", 
              index=False, sep=";", encoding="utf-8")

Year: 2017
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5569 entries, 0 to 5568
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5569 non-null   object
 1   Populaçăo                 5569 non-null   int64
 2   1.1_%R.Líquida_Total      5569 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5569 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5569 non-null   float64
 5   2.3_%D.com_Medicamentos   5569 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5569 non-null   float64
 7   2.5_%D.Invest/D.Total     5569 non-null   float64
 8   R.Transf.SUS              5569 non-null   float64
 9   D.R.Próprios              5569 non-null   float64
 10  D.Total_Saúde             5569 non-null   float64
 11  cod_municipio             5569 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 522.2+ KB
None
Year: 2013
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5568 entries, 0 to 5567
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5568 non-null   object
 1   Populaçăo                 5568 non-null   int64
 2   1.1_%R.Líquida_Total      5568 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5568 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5568 non-null   float64
 5   2.3_%D.com_Medicamentos   5568 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5568 non-null   float64
 7   2.5_%D.Invest/D.Total     5568 non-null   float64
 8   R.Transf.SUS              5568 non-null   float64
 9   D.R.Próprios              5568 non-null   float64
 10  D.Total_Saúde             5568 non-null   float64
 11  cod_municipio             5568 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 522.1+ KB
None
Year: 2011
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5526 entries, 0 to 5525
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5526 non-null   object
 1   Populaçăo                 5526 non-null   int64
 2   1.1_%R.Líquida_Total      5526 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5526 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5526 non-null   float64
 5   2.3_%D.com_Medicamentos   5526 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5526 non-null   float64
 7   2.5_%D.Invest/D.Total     5526 non-null   float64
 8   R.Transf.SUS              5526 non-null   float64
 9   D.R.Próprios              5526 non-null   float64
 10  D.Total_Saúde             5526 non-null   float64
 11  cod_municipio             5526 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 518.2+ KB
None
Year: 2010
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5544 entries, 0 to 5543
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5544 non-null   object
 1   Populaçăo                 5544 non-null   int64
 2   1.1_%R.Líquida_Total      5544 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5544 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5544 non-null   float64
 5   2.3_%D.com_Medicamentos   5544 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5544 non-null   float64
 7   2.5_%D.Invest/D.Total     5544 non-null   float64
 8   R.Transf.SUS              5544 non-null   float64
 9   D.R.Próprios              5544 non-null   float64
 10  D.Total_Saúde             5544 non-null   float64
 11  cod_municipio             5544 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 519.9+ KB
None
Year: 2012
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5446 entries, 0 to 5445
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5446 non-null   object
 1   Populaçăo                 5446 non-null   int64
 2   1.1_%R.Líquida_Total      5446 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5446 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5446 non-null   float64
 5   2.3_%D.com_Medicamentos   5446 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5446 non-null   float64
 7   2.5_%D.Invest/D.Total     5446 non-null   float64
 8   R.Transf.SUS              5446 non-null   float64
 9   D.R.Próprios              5446 non-null   float64
 10  D.Total_Saúde             5446 non-null   float64
 11  cod_municipio             5446 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 510.7+ KB
None
Year: 2009
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5549 entries, 0 to 5548
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5549 non-null   object
 1   Populaçăo                 5549 non-null   int64
 2   1.1_%R.Líquida_Total      5549 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5549 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5549 non-null   float64
 5   2.3_%D.com_Medicamentos   5549 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5549 non-null   float64
 7   2.5_%D.Invest/D.Total     5549 non-null   float64
 8   R.Transf.SUS              5549 non-null   float64
 9   D.R.Próprios              5549 non-null   float64
 10  D.Total_Saúde             5549 non-null   float64
 11  cod_municipio             5549 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 520.3+ KB
None
Year: 2018
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5569 entries, 0 to 5568
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5569 non-null   object
 1   Populaçăo                 5569 non-null   int64
 2   1.1_%R.Líquida_Total      5569 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5569 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5569 non-null   float64
 5   2.3_%D.com_Medicamentos   5569 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5569 non-null   float64
 7   2.5_%D.Invest/D.Total     5569 non-null   float64
 8   R.Transf.SUS              5569 non-null   float64
 9   D.R.Próprios              5569 non-null   float64
 10  D.Total_Saúde             5569 non-null   float64
 11  cod_municipio             5569 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 522.2+ KB
None
Year: 2014
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5569 entries, 0 to 5568
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5569 non-null   object
 1   Populaçăo                 5569 non-null   int64
 2   1.1_%R.Líquida_Total      5569 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5569 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5569 non-null   float64
 5   2.3_%D.com_Medicamentos   5569 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5569 non-null   float64
 7   2.5_%D.Invest/D.Total     5569 non-null   float64
 8   R.Transf.SUS              5569 non-null   float64
 9   D.R.Próprios              5569 non-null   float64
 10  D.Total_Saúde             5569 non-null   float64
 11  cod_municipio             5569 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 522.2+ KB
None
Year: 2015
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5569 entries, 0 to 5568
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5569 non-null   object
 1   Populaçăo                 5569 non-null   int64
 2   1.1_%R.Líquida_Total      5569 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5569 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5569 non-null   float64
 5   2.3_%D.com_Medicamentos   5569 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5569 non-null   float64
 7   2.5_%D.Invest/D.Total     5569 non-null   float64
 8   R.Transf.SUS              5569 non-null   float64
 9   D.R.Próprios              5569 non-null   float64
 10  D.Total_Saúde             5569 non-null   float64
 11  cod_municipio             5569 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 522.2+ KB
None
Year: 2016
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5537 entries, 0 to 5536
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5537 non-null   object
 1   Populaçăo                 5537 non-null   int64
 2   1.1_%R.Líquida_Total      5537 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5537 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5537 non-null   float64
 5   2.3_%D.com_Medicamentos   5537 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5537 non-null   float64
 7   2.5_%D.Invest/D.Total     5537 non-null   float64
 8   R.Transf.SUS              5537 non-null   float64
 9   D.R.Próprios              5537 non-null   float64
 10  D.Total_Saúde             5537 non-null   float64
 11  cod_municipio             5537 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 519.2+ KB
None

Year: 2019
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5556 entries, 0 to 5555
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Munic-BR                  5556 non-null   object
 1   Populaçăo                 5556 non-null   int64
 2   1.1_%R.Líquida_Total      5556 non-null   float64
 3   2.1_D.Total_Saúde/Hab     5556 non-null   float64
 4   2.2_%D.Pessoal/D.Total    5555 non-null   float64
 5   2.3_%D.com_Medicamentos   5555 non-null   float64
 6   2.4_%D.Serv.Terc/D.Total  5555 non-null   float64
 7   2.5_%D.Invest/D.Total     5555 non-null   float64
 8   R.Transf.SUS              5556 non-null   float64
 9   D.R.Próprios              5556 non-null   float64
 10  D.Total_Saúde             5556 non-null   float64
 11  cod_municipio             5556 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 521.0+ KB
None